# Below is the list of the component images with the digest. These need to be updated manually
# whenever a new bundle image is required (required also for releasing the index images).
# Make use of the `registry.stage.redhat.io` repository for using stage images and `registry.redhat.io` for prod images.
# This is currently sourced in `hack/bundle/render_templates.sh` to update the image references in the operator CSV.

# cert-manager operator image digest.
CERT_MANAGER_OPERATOR_IMAGE=registry.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:207804f9237b0c2875f5252997312230c88726b5271c6419320958078dd7b7fd

# cert-manager operand - webhook component image digest.
CERT_MANAGER_WEBHOOK_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d

# cert-manager operand - cainjector component image digest.
CERT_MANAGER_CA_INJECTOR_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d

# cert-manager operand - controller component image digest.
CERT_MANAGER_CONTROLLER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:b3305a06bff4a344ba1b19c8142d7e605fc723841981c97aab2310ff8a82c66d

# cert-manager operand - acmesolver component image digest.
CERT_MANAGER_ACMESOLVER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:8ce8e3f21e49fda94f6c984e4777637e3773a099c6d74010a26e5e2743965739

# cert-manager-istiocsr operand image digest.
CERT_MANAGER_ISTIOCSR_IMAGE=registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:f63c50a7465ce4222dc3bb9443056d5bfcb07ecba20fcd9dd6ee143bc591f446

# cert-manager trust-manager operand image digest.
CERT_MANAGER_TRUST_MANAGER_IMAGE=registry.redhat.io/cert-manager/cert-manager-trust-manager-rhel9@sha256:1fef2bffce8c89631099fbf8cefaa031502d670817897660ccfa0a9aa8a9ebc7
