apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    build.appstudio.openshift.io/repo: https://github.com/openshift/cert-manager-operator-release?rev={{revision}}
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-1.14" && (".tekton/cert-manager-operator-1-14-push.yaml".pathChanged()
      || "Containerfile.cert-manager-operator".pathChanged() || "cert-manager-operator/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cert-manager-operator-1-14
    appstudio.openshift.io/component: cert-manager-operator-1-14
    pipelines.appstudio.openshift.io/type: build
  name: cert-manager-operator-1-14-on-push
  namespace: cert-manager-oape-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cert-manager-oape-tenant/cert-manager-operator-1-14/cert-manager-operator-1-14:{{revision}}
  - name: dockerfile
    value: Containerfile.cert-manager-operator
  - name: path-context
    value: .
  - name: build-args
    value:
    - RELEASE_VERSION=v1.14.2
    - COMMIT_SHA={{revision}}
    - SOURCE_URL={{source_url}}
  pipelineRef:
    name: multi-arch-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-cert-manager-operator-1-14
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
