apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cert-manager-operator-release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-1.19" && (".tekton/cert-manager-trust-manager-1-19-push.yaml".pathChanged() ||
      "Containerfile.cert-manager-trust-manager".pathChanged() || "trust-manager".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cert-manager-trust-manager-1-19
    appstudio.openshift.io/component: cert-manager-trust-manager-1-19
    pipelines.appstudio.openshift.io/type: build
  name: cert-manager-trust-manager-1-19-on-push
  namespace: cert-manager-oape-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cert-manager-oape-tenant/cert-manager-trust-manager-1-19/cert-manager-trust-manager-1-19:{{revision}}
  - name: dockerfile
    value: Containerfile.cert-manager-trust-manager
  - name: path-context
    value: .
  - name: build-args
    value:
    - RELEASE_VERSION=v0.20.3
    - COMMIT_SHA={{revision}}
    - SOURCE_URL={{source_url}}
  - name: prefetch-input
    value: '{"type": "gomod", "path": "trust-manager"}'
  - name: snyk-org-id
    value: "b6dda4fc-c9ea-48da-ac45-67f75f258e5a"
  - name: snyk-proj-name
    value: "cert-manager-trust-manager"
  pipelineRef:
    name: multi-arch-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-cert-manager-trust-manager-1-19
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
